### ISSUE TITLE
'WSA' does not exist in UnityEngine.VR 

### ISSUE THREAD

**Issue by Arthurwiz** [Microsoft/GalaxyExplorer#10]
I'm trying to build the project and I could not pass this error when trying to build it in Unity.

Here are my specs:
Windows 10 Pro
Unity beta version: 5.4.0b13
VS Community 2015 Upgrade 2

This is what I did:
1) Unzip the GalaxyExplorer
2) Open it with Unity [C:\Program Files\Unity 5.4.0b13]
3) When building with these settings: Windows Store ---> SDK: Universal 1.0, UWP Build Type: D3D, Build and Run on: Local Machine
Here are some of the errors that I encountered:

Assets/Scripts/Input/GazeSelectionTarget.cs(4,22): error CS0234: The type or namespace name `WSA' does not exist in the namespace `UnityEngine.VR'. Are you missing an assembly reference?

Assets/Scripts/Input/HandInput.cs(6,22): error CS0234: The type or namespace name `WSA' does not exist in the namespace `UnityEngine.VR'. Are you missing an assembly reference?

Assets/Scripts/Input/InputRouter.cs(7,22): error CS0234: The type or namespace name `WSA' does not exist in the namespace `UnityEngine.VR'. Are you missing an assembly reference?

Any clues are helpful.  Thanks!

**Comment by bjmalicoat** [comment]
Did you download the Unity Editor linked from http://lens.ms/Sa37sr ?

**Comment by Arthurwiz** [comment]
@bjmalicoat Thank you!

**Comment by Jaychouxq** [comment]
> Did you download the Unity Editor linked from http://lens.ms/Sa37sr ?

Is this website invalid？
