### ISSUE TITLE
Unable to build due to error signing the project

### ISSUE THREAD

**Issue by DavidShoe** [Microsoft/GalaxyExplorer#107]
Severity	Code	Description	Project	File	Line	Suppression State
Error		An error occurred while signing: Failed to sign bin\Release\app.publish\GE_POIMaker.exe. SignTool Error: No certificates were found that met all the given criteria.	GE_POIMaker

**Comment by timGerken** [comment]
Unless you're trying to actually build GE_POIMaker, a temporary workaround is to right click on that project in Visual Studio and select "Unload Project".

**Comment by Eg-Virus** [comment]
I have this issue as well.

**Comment by timGerken** [comment]
Please try the work around listed for this issue for now.

Sent from my Windows 10 phone

________________________________

**Comment by elitemn** [comment]
This is due to the expiration of the test certificate. This certificate should be replaced by a certificate issued by a commercial CA, with a valid trust chain. A temporary work-around would be to reissue the test certificate and build the application.

**Comment by timGerken** [comment]
Alternately, completely removing the signing requirement seems to solve the problem equally well.

**Comment by Eg-Virus** [comment]
The Workaround works.
