### ISSUE TITLE
Sagitarius A* could use a better visualization

### ISSUE THREAD

**Issue by timGerken** [microsoft/GalaxyExplorer#112]
The current visualization uses really big versions of our Solar System's Sun's solar flares. At times, this visualization has difficulty maintaining 60FPS on HoloLens.

**Comment by elitemn** [comment]
Yes indeed, and it is not as "pretty" or imaginative as I would like.  An easy fix would be to get rid of the large flares (it is supposed to approximate an event horizon, with weirdness, I thought it looked kind of cool when walking around it, and it was different) in favor of the "standard" depiction of an accretion disc, or just a thin light border around a dark sphere. Thoughts? Suggestions?

**Comment by timGerken** [comment]
I love the "differentness" of the effect. I, however, have zero artistic talent and hope the rest of the community can pitch in here.

**Comment by timGerken** [comment]
This is updated in #118

**Comment by jessemcculloch** [comment]
No longer relevant with latest version of Galaxy Explorer
