### ISSUE TITLE
Unloaded Projects

### ISSUE THREAD

**Issue by Eg-Virus** [Microsoft/GalaxyExplorer#113]
Hi,
i just downloaded the code and tried to load the solution but there's 2 projects couldn't loaded because one is not there and that would be **Assembly-CSharp** and the other is Glaxy Explorer because it can't find the file **UnityCommon.props**

i don't know if i missing anything or not, but i installed everything based on the instructions from this [Install the tools](https://developer.microsoft.com/en-us/windows/mixed-reality/install_the_tools?Ocid=Hololens%20-%20Education_Social_TWITTER_HoloLens_20160330_413089651)

**Comment by timGerken** [comment]
Which version of Unity are you using?

________________________________

**Comment by Eg-Virus** [comment]
I'm using 
Windows 10 Version 1709,Build 16299.125
Unity version 2017.3.0f3
VS 2017 version 15.5.2

**Comment by timGerken** [comment]
What are the settings in the build settings… dialog in unity?

Sent from my Windows 10 phone

________________________________

**Comment by Eg-Virus** [comment]
My bad, i thought that everything is already built and ready to run because it big size solution(i didn't read the readme from the github).
i loaded the projects after building it from Unity and facing different problem now :)
  
Sorry for wasting your time.
