### ISSUE TITLE
Port Galaxy Explorer to current HoloToolKit

### ISSUE THREAD

**Issue by timGerken** [microsoft/GalaxyExplorer#116]
Galaxy Explorer was released on a very early (pre-release) incarnation of the HoloToolKit.

It would be great if we could either port the existing project to the current HoloToolKit (aka legacy MRTK) or re-build the app from the ground up on said HTK.

**Comment by timGerken** [comment]
This is addressed in #118

**Comment by jessemcculloch** [comment]
No longer relevant with latest version of Galaxy Explorer
