### ISSUE TITLE
Some textures need a change so opening clean project loads without warnings

### ISSUE THREAD

**Issue by timGerken** [microsoft/GalaxyExplorer#119]
![image](https://user-images.githubusercontent.com/14828396/50521101-f362a080-0abb-11e9-9957-63e289fe0733.png)

Note: when this dialogue appears, do NOT click the "Fix now" button. It will make Jupiter and Mars look terrible.

**Comment by timGerken** [comment]
fixed in #118

**Comment by keveleigh** [comment]
Whoops, re-opening until #118 is merged.
