### ISSUE TITLE
Supplied PxGeometry is not valid

### ISSUE THREAD

**Issue by baloodevil** [Microsoft/GalaxyExplorer#12]
I receive an error when trying to load the GalaxyExplorer in Hololens emulator.

```
Supplied PxGeometry is not valid. Shape creation method returns NULL.
(Filename: C:/buildslave/physx/build/Source/PhysX/src/NpFactory.cpp Line: 675)
The program '[3624] GalaxyExplorer.exe' has exited with code -1 (0xffffffff).
```

I followed the instructions in the [channel 9 tutorial](https://channel9.msdn.com/Blogs/AdamsGarage/Getting-Started-with-the-HoloLens), with the exception that I git cloned the project, instead of downloading a zip.  The emulator starts, 'pinning Earth to the middle of the room', it starts to zoom out to the solar system, video freezes (its cold in space!) right after 'is part of an even bigger picture', and throws the error above.  Using HoloLens Emulator 10.0.11082.1039.

**Comment by jadack-msft** [comment]
Are you deploying a debug version of Galaxy Explorer to the emulator? From the README:

"From Visual Studio, set the Configuration to Release for faster builds (doesn't use .NET Native) or Master to build the type of package the Store needs (uses .NET Native). Make sure to change ARM or x64 to x86. Now you can deploy to the Emulator, a Remote Device, or create a Store package to deploy at a later time."

**Comment by baloodevil** [comment]
Selecting "Release" solved the problem.  Thank you.
