### ISSUE TITLE
Splash screen jitter

### ISSUE THREAD

**Issue by timGerken** [microsoft/GalaxyExplorer#121]
Splash screen in HoloLens and MR looks great
In desktop though it jitters

**Repro steps:**
Launch app in desktop platform, observe hologram splash screen at the end it jitters badly before Logo of app appears

**Comment by timGerken** [comment]
This seems to be a bug in the current build(s) of Unity.

1. On the original GE, this splash screen never even appeared when running on desktop. For some reason it does now.
2. There is no apparent way to access this funcionality in order to disable it.

**Comment by jessemcculloch** [comment]
No longer relevant with latest version of Galaxy Explorer
