### ISSUE TITLE
Once HoloToolkit 2017.4.4.0 is released need to remove HTK from project and use Nuget instead

### ISSUE THREAD

**Issue by timGerken** [microsoft/GalaxyExplorer#126]
GE currently relies on a change slated for HTK 2017.4.4.0.
[https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/53b43c9d53db0da9279049c24e5fa9dbf0cef228](https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/53b43c9d53db0da9279049c24e5fa9dbf0cef228)
Once that version of the HTK has been released, we should remove the HTK from the GE project and instead fetch it via NuGet for Unity.

**Comment by jessemcculloch** [comment]
New version of Galaxy Explorer upgrades to MRTK v2
