### ISSUE TITLE
Download issues

### ISSUE THREAD

**Issue by MuthiahKa** [Microsoft/GalaxyExplorer#13]
Unable to download the Galaxy explorer app. Now during the third attempt,  it got struck at 47% for the past 1 hour. How long does it really take to download this?. Please advise

**Comment by ChimeraScorn** [comment]
To be clear, are you having trouble downloading from the store, or syncing the repo?

**Comment by MuthiahKa** [comment]
Thanks for your follow up.
After using the hard wired network cable to the router, in stead of wireless connection, the down load process could complete with in 4 minutes. There could be problem in my wireless network. So we can close this issue.
