### ISSUE TITLE
Error in Unity when building project: "Unknown version control plugin: Tfs"

### ISSUE THREAD

**Issue by timkeosa** [Microsoft/GalaxyExplorer#20]
This error message is generated by Unity while building GalaxyExplorer, but doesn't appear to have any impact on the build.

A thread on the [HoloLens forums](https://forums.hololens.com/discussion/comment/1642#Comment_1642) discusses this issue.

**Comment by timGerken** [comment]
this is resolved in Microsoft/phone with #29

**Comment by timGerken** [comment]
closed via #56
