### ISSUE TITLE
Error in Unity when building project: "Broken text PPtr in file..."

### ISSUE THREAD

**Issue by timkeosa** [Microsoft/GalaxyExplorer#21]
This error is generated in Unity when building GalaxyExplorer for the first time causing the build to fail. However, subsequent builds of the project won't hit this error and successfully generate the Visual Studio Solution. Work-around is to simply build in Unity twice.

A [HoloLens forum thread](https://forums.hololens.com/discussion/comment/2102#Comment_2102) covers this error in more detail.

The complete error message is: "Broken text PPtr in file(Assets/SolarSystem/SolarSystem.prefab). Local file identifier (11493526) doesn't exist!"

**Comment by timGerken** [comment]
This is resolved as part of #28, currently in the phone branch.

**Comment by timGerken** [comment]
closed via #56
