### ISSUE TITLE
Error in Unity when building project: "Component MonoBehaviour could not be loaded..."

### ISSUE THREAD

**Issue by timkeosa** [Microsoft/GalaxyExplorer#22]
This strange error occurs when building GalaxyExplorer in Unity, but it doesn't cause the build to fail and doesn't appear to have any impact on Galaxy Explorer.

Complete error message is: "Component MonoBehaviour could not be loaded when loading game object. Cleaning up!"

**Comment by timGerken** [comment]
closed (or not-reproducible) via #56
