### ISSUE TITLE
MoveCube Button make gaze  behave abnormal.

### ISSUE THREAD

**Issue by zwxbest** [Microsoft/GalaxyExplorer#36]
The card will not show until my gaze precisely on "UI_POI" Collider,is this normal?
but
when I use moveCube button to move the galaxy  two or more times,the card shows when gaze UI don't move on the "UI_POI" Collider,gaze UI is On  "UI_POI"'s left or right.
maybe my network reason,I can't upload my screenshot,so I use this link
http://7xngf3.com1.z0.glb.clouddn.com/galaxy_Bug.PNG

**Comment by zwxbest** [comment]
I think I solved this,chang GazeCursor GameObject 's Cursor Script‘s Prioritied Cursor Mask ,change Sphere Cast Search  To Raycast Search.

**Comment by timGerken** [comment]
It is difficult for me to determine the issue you are describing.
- Gaze selection happens in GazeSelectionManager.cs and GazeSelection.cs on the Input GO (GazeCursor's parent).
- GazeSelection.SphericalConeSearch is what's causing the POI to be selected when the cursor is near it.
- That only seems to happen when the cursor is on the Galaxy background (plane), and not when what is behind the POI is nothing.
