### ISSUE TITLE
Create releases with pre-compiled appx for quick deployment

### ISSUE THREAD

**Issue by dotMorten** [Microsoft/GalaxyExplorer#4]
Please compile the appx and place it under the "releases" tab for quicker deployment.

**Comment by ThitherCrane** [comment]
If compiled, how will users see the code?

**Comment by dotMorten** [comment]
Errrr? the way they do it right now would work. Not asking for a replacement, but a quick getting started.

**Comment by dotMorten** [comment]
Personally I'm struggling with getting it to compile but I'm more anxious to get the app deployed to my HoloLens the moment it landed on my doorstep. Experience with the device and it's apps comes first. Building apps and deconstructing source code comes after.
Alternatively just put it in the store.

**Comment by jadack-msft** [comment]
Galaxy Explorer is available on the Windows Store for HoloLens devices.

**Comment by dotMorten** [comment]
Really? I didn't see it there. Only 6 apps are shown.

**Comment by dotMorten** [comment]
Found it!
