### ISSUE TITLE
POI Card creator tool needed

### ISSUE THREAD

**Issue by timGerken** [Microsoft/GalaxyExplorer#43]
It would be incredibly helpful to have a tool that, given two strings for input, automatically spits out a .PNG file for the POI card.

**Comment by elitemn** [comment]
This is definitely needed. I'd like to learn how to do this anyway.

**Comment by timGerken** [comment]
That would be awesome!

**Comment by timGerken** [comment]
Hey @elitemn, have you been able to make any progress on this tool?

**Comment by elitemn** [comment]
Hi @timGerken, I have a working tool, but I am not satisfied with the font I am using, how would I go about finding the original font you folks used fort he billboards? The closest I could find was "OCR A Extended", but it would be nice to match 100%

**Comment by timGerken** [comment]
Hi @elitemn, I just received this from one of the original GE devs:

> Here is the font: https://fonts.google.com/specimen/Orbitron or https://www.fontsquirrel.com/fonts/Orbitron 

> I don’t think it was ever checked, but [here](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web) is the license.

**Comment by elitemn** [comment]
Excellent Thanks @timGerken ! Should I include the POI maker as an added project to GE?

**Comment by timGerken** [comment]
Yes, that's the way I envisioned the POI maker tool living with GE. At this point, hold off on adding the actual font. Instead, add a readme pointing to where to install the font and make that a prerequisite for running the tool. I'm double-checking to see if the license the font was released under is compatible with the MIT licence that GE is under.

**Comment by elitemn** [comment]
@timGerken  Just created a pull request for this, check it out.

**Comment by timGerken** [comment]
Hi @elitemn ,
are you ready to reissue your PR?
I'd love to get the tool added to the GE codebase and re-create all the POIs!

**Comment by elitemn** [comment]
Yes, I'll open a PR today.

**Comment by timGerken** [comment]
Closed via #69. Thanks @elitemn !
