### ISSUE TITLE
Making progress

### ISSUE THREAD

**Issue by ThitherCrane** [Microsoft/GalaxyExplorer#5]
I can make this. How to progress and make it look like the earth-moon animation?
![myplanet](https://cloud.githubusercontent.com/assets/18190665/14229589/2de5f098-f905-11e5-90ce-91642c9bae7a.JPG)
 starting from here?

**Comment by ThitherCrane** [comment]
Created a rolling ball that uses script in C # !
[ball](https://cloud.githubusercontent.com/assets/18190665/14230618/8fd4f38a-f92d-11e5-931a-829b70b4277e.JPG)

**Comment by ChimeraScorn** [comment]
Hey Thither, 

Closing this since it is not an issue tracking an improvement to the application.  

-C
