### ISSUE TITLE
GalacticCenter POIs need better spacing

### ISSUE THREAD

**Issue by timGerken** [Microsoft/GalaxyExplorer#72]
These POIs and their cards are grouped a bit too close together. They should be spread out some so they are easier to select.

**Comment by elitemn** [comment]
Adjusted x value of indicator offset (POI). This meets the requirement of spreading indicators (and billboards) out a bit.

**Comment by timGerken** [comment]
Interesting choice!

**Comment by elitemn** [comment]
:)... I initially tried to move the indicators (indicator and line bottom x,y values), but when I got it to look in just the right position, there was way too much artificial parallax when moving relative to the indicators. I realize this is inconsistent with the rest of the POIs, but at least they should be more "selectable".
