### ISSUE TITLE
Could not follow guide to build

### ISSUE THREAD

**Issue by nonew** [Microsoft/GalaxyExplorer#74]
Hello, HoloLens team
I met several problems while building the Galaxy Explorer project:
1. From Unity, in Build Settings window. I could not find:
1.1 "any device" as the Target device
1.2 "Copy References" to check

If I ignore and continue, when I build output C# project in VS 2015, the 2nd problem happen:
2. "UnityPlayer", "AppCallbacks" and "WinRTBridge" assembly reference could not be found
but I can find them in corresponding folder C:\Program Files\Unity HoloLens 5.4.0f3-HTP\Editor\Data\PlaybackEngines\MetroSupport\Players\UAP\

I am using Unity Technical Preview version HoloLens 5.4.0f3-HTP from Microsoft guidance. When open C# project it prompt me the version is not match need to re-import...

If I add  manually to those assembly reference, VS 2015 prompt me "A reference to ....dll could not be added. Please make sure that file is accessible..." 

Could you guys help me out of here? 

Thank you
BR
Kevin

**Comment by elitemn** [comment]
Try Unity version 5.5.0b4

**Comment by Camuvingian** [comment]
Did you manage to fix this problem?

**Comment by nonew** [comment]
Finally I managed to get it worked in a new Win10 machine with following config:
-OS Windows 10 (10.0.14393) 64bit with latest update

-VS 2015 community with update 3 (with Windows 10 SDK 10.0.10586 checked)
https://www.visualstudio.com/downloads/

-Unity 5.5.0f1
https://unity3d.com/unity/beta#download

-HoloLens Emulator
http://go.microsoft.com/fwlink/?LinkID=823018

-Windows 10 SDK
https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk

-Turn On "Developer Mode" in Win10 Settings (need restart to take effect)

Now I can pass build and run in simulator.  Hope it help.

nonew@2016.11.23

**Comment by nonew** [comment]
One issue: no audio output when run in simulator.
Here is  VS output , I'm not sure if it is bug in Unity 5.
-----------------------------------------------------------------------
Audio source failed to initialize audio spatializer. An audio spatializer is specified in the audio project settings, but the associated plugin was not found or initialized properly. Please make sure that the selected spatializer is compatible with the target.
 
(Filename: C:/buildslave/unity/build/Runtime/Audio/AudioSource.cpp Line: 348)
-----------------------------------------------------------------------

nonew@2016.11.23

**Comment by elitemn** [comment]
For those of you struggling with this: There is a missing step when installing the latest unity on a clean dev machine (for 5.5.0f3)  - Install the unity metro support package:
[Unity Metro Support Package 5.5.0f3](http://download.unity3d.com/download_unity/38b4efef76f0/TargetSupportInstaller/UnitySetup-Metro-Support-for-Editor-5.5.0f3.exe)
