### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by sessa** [Microsoft/GalaxyExplorer#79]
Hi, I am receiving this error in unity's console:

```
NullReferenceException: Object reference not set to an instance of an object
IntroductionFlow.Start() (at Assets/Scripts/IntroductionFlow.cs:93)
```

https://github.com/Microsoft/GalaxyExplorer/blob/master/Assets/Scripts/IntroductionFlow.cs#L92
```
     92:   ViewLoader.Instance.CoreSystemsLoaded += CoreSystemsLoaded;
```

I have not touched the cloned repo, I am using Unity 5.5.0f3.

**Comment by timGerken** [comment]
Interesting, I'm not able to reproduce this behavior (clean clone of Microsoft/master).
Are you seeing this on device, emulator or in the Unity Editor.
In my attempt, the Unity Editor just froze after hitting the play-mode button (nothing output on the console). This may (or may not) be related to what you are seeing.
@elitemn , can you reproduce this issue?

**Comment by sessa** [comment]
@timGerken -- The error appears in the Unity Console.  

When I run the project in VS in the Emulator, it loads the unity loading screen then goes black.  Also, when running it as a standalone application, unity screen loads, and then the console output in the standalone windows app shows the same error.

Let me reclone and retry once more.  Will report back after.

**Comment by elitemn** [comment]
Fresh dev build, Unity 5.5.0f3, HoloLens emulator 10.0.14393.0,  HoloLens device and emulator works as expected. @sessa, can you confirm your emulator build?
@timGerken, I can play from the main scene in unity just fine, intro, solar system view then to galaxy view.  I can't seem to select a POI in galaxy view from unity.
