### ISSUE TITLE
A question of the ViewLoader.cs

### ISSUE THREAD

**Issue by jasonyslai** [Microsoft/GalaxyExplorer#8]
Why do it need to store event handler to the private event (_coreSystemsLoaded) before the Core system loaded?

**Comment by ThitherCrane** [comment]
Please explain more.

**Comment by jasonyslai** [comment]
Thank you for response:D

 public event Action CoreSystemsLoaded
    {

        add
        {
            if (coreSystemsLoaded)                   // Here! i don't understand this statement
            {
                value();  
            }
            else
            {
                _coreSystemsLoaded += value;  //Why it need to store it to private event
            }
        }

        remove
        {
            _coreSystemsLoaded -= value;  // after the Core system is loaded, 
                                                               // it still trying to remove the Null event.
                                                               // Such as "IntroductionFlow.cs" Line 206
                                                               // ViewLoader.Instance.CoreSystemsLoaded -= CoreSystemsLoaded;
        }
    }

**Comment by ThitherCrane** [comment]
Possibly this explanation: https://github.com/Microsoft/GalaxyExplorer/blob/master/Assets/Scripts/ViewLoader.cs
![explain](https://cloud.githubusercontent.com/assets/18190665/14319193/47e72918-fbde-11e5-96cf-dccb414e7109.JPG)

**Comment by jadack-msft** [comment]
This is a programming paradigm with EventHandlers that calls delegates when registering for an event if the impetus for the event has already triggered. 

In this case, any class can register to be notified when Core systems are loaded, and if the Core systems are already loaded then the delegate will be called immediately. If the Core systems are not loaded, then the delegate will be called when they are.

**Comment by jasonyslai** [comment]
Hi @jadack-msft , Thanks for your explanation :)!
Sorry for my stupidity^^'.
Would u mind telling me what's the difference between

    value();

and 

    _coreSystemsLoaded += value;

**Comment by jadack-msft** [comment]
value is the delegate to be called when the event is triggered. The first context is calling the delegate directly, while the second registers the delegate with the event. All registered delegates are called at line 183 in ViewLoader.cs.

**Comment by ThitherCrane** [comment]
jadack-msft : If delegates must be registered before being called, is this the reason why some Microsoft apps (e.g., weather or Xbox) must be clicked twice to work properly?

**Comment by ChimeraScorn** [comment]
Delegates needing to be registered is a programming construct... It does not have a direct impact on an app behavior, beyond what the developer intends.  An app level behavior like you are describing cannot be ascribed to the semantics of a particular programming construct.

**Comment by jasonyslai** [comment]
@jadack-msft Thank you! I think i got the usage of this accessor structure.
**Directly or Manually call delegates :D?**
