### ISSUE TITLE
Component  could not be loaded when loading game object. Cleaning up!

### ISSUE THREAD

**Issue by NadirYaqoob** [Microsoft/GalaxyExplorer#85]
i have 2 problems 
1 Component  could not be loaded when loading game object. Cleaning up!
2 Transform component could not be found on game object. Adding one!

how to solve it ?

**Comment by timGerken** [comment]
Where and when do you see these messages?
Which release of Unity are you using?

**Comment by dunaij93** [comment]
i have got the same problem, and i am using unity 2018.3.8f1
