### ISSUE TITLE
Error building Player because scripts have compile errors in the editor

### ISSUE THREAD

**Issue by javiertorres7** [Microsoft/GalaxyExplorer#88]
I am trying to complete the building step, but it says that I need to fix some compile errors in the scripts, even though, I did not mess with code in the scripts. I also I do not know how to look for the errors in the scripts. I am using Visual Studio 2015 as my editor and I don't see any errors.

**Comment by javiertorres7** [comment]
I am using Unity 5.50f3 (64bit) by the way.

**Comment by timGerken** [comment]
Hi @javiertorres7 ,
Can you give a little more detail about the errors that the Unity console is reporting? Maybe attach a screen shot? Unity 5.5.0f3 is the correct version of Unity (projectversion.txt). I exclusively use 64-bit.
Thanks!
Tim

**Comment by javiertorres7** [comment]
Yes, of course! I attached the screenshot down below. Thanks!


Javier Torres

**Comment by timGerken** [comment]
@javiertorres7 
Hmm. I'm not seeing the screenshot.

**Comment by javiertorres7** [comment]
![uniiii](https://cloud.githubusercontent.com/assets/23087965/26432816/0e3c3628-40c4-11e7-8095-3fb46f52c01c.PNG)

**Comment by timGerken** [comment]
@javiertorres7 
You are probably being affected by the details described in [this thread](https://forum.unity3d.com/threads/suddenly-unable-to-build-solutions-anymore.466066/). I just made a commit in Master to work with Unity 5.5.1p4 and Visual Studio 2017. Please let me know if these changes also resolve the issue you describe here.
