### ISSUE TITLE
I would like to use GalaxyExplorer in lesson

### ISSUE THREAD

**Issue by weed** [Microsoft/GalaxyExplorer#91]
Dear **Microsoft GalaxyExplorer team**,
I am **Tatsuro Ueda**, Japanese.

Nice to meet you.
I was a teacher for ten years and now I am developing a science
learning application.
I am planning to visit junior high school and high school,
and to **teach an hour class using HoloLens**.
For the time being, I am thinking to try classes for free until the
end of March next year.

In these lessons, I would like to use **GalaxyExplorer** in addition to
**HoloMagnet3** I developed.
I would be pleased if you grant permission.
Thank you very much.

In addition, I will carry out a simple questionnaire survey at the end
of the class.
If you grant permission, I think that **I can send you the impression of
GalaxyExplorer**.

Best regards
Tatsuro Ueda

---
植田達郎（Tatsuro Ueda）
物理教材アプリ開発者
Physics education app developer
tatsuro.ueda@feelphysics.education
(+81) 080-4387-0629
http://blog.jp.feelphysics.education

**Comment by timGerken** [comment]
Greetings Tatsuro Ueda,

That is totally awesome and thank you for asking!
The license that Galaxy Explorer is published with grants you the ability to use it as you will.
We are interested in seeing what your students' impressions of Galaxy Explorer are.
Perhaps the rest of the open source community here can help bring their new ideas to the application.

Best regards,
Tim Gerken

@weed 
@ChimeraScorn

**Comment by weed** [comment]
Dear Tim Gerken,

Thank you for your peace of mind. 
I am glad that I could use GalaxyExplorer for my lesson. 
Looking at the galaxy from the side, I'd like to teach "This is Milky Way!" 
I'm going to start translating messages from now on. 
I will do my best to tell you students' impressions and requests

Best regards,
Tatsuro Ueda

@timGerken
