### ISSUE TITLE
Build Fails 2017.2.0f3-MRTP3 WIN10 SDK 10.0.16299.0

### ISSUE THREAD

**Issue by RapukeMoana** [Microsoft/GalaxyExplorer#97]
Following error on build. Runs in Unity.
Exception: Failed to locate env variables VS140COMNTOOLS or VS120COMNTOOLS.
Utility.GetVSVersion () (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/Utility.cs:623)
MetroCSharpVisualStudioSolutionCreator.WriteSolutionFile (System.String solutionFileName, UnityEditor.Scripting.ScriptCompilation.ScriptAssembly[] csharpAssemblies) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/MetroCSharpVisualStudioSolutionCreator.cs:196)
MetroCSharpVisualStudioSolutionCreator.CreateSolutionFileFrom () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/MetroCSharpVisualStudioSolutionCreator.cs:724)
PostProcessWSA.CreateVisualStudioSolution () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWSA.cs:320)
PostProcessWinRT.Process () (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/PostProcessWinRT.cs:237)
UnityEditor.WSA.BuildPostprocessor.DoPostProcess (BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:142)
UnityEditor.WSA.BuildPostprocessor.PostProcess (BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:149)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by timGerken** [comment]
Can you provide a little more detail?
It looks like it is the build step from Unity that is failing for you.
Do you have Visual Studio 2017 installed? Do you have any other version of VS installed?
On which branch are you seeing this? master or MixedReality?

**Comment by RapukeMoana** [comment]
Yes I have VS 2017 and today upgraded to 15.4.2 from 15.4.1. I have no other VS in fact this is a very new clean Surface Pro. I uninstalled Unity and reinstalled 2017.2.0f3-MRTP3. Windows is 1709 16299.19. Very frustrating but that said I am very happy to see this branch as I have plans to build onto it. I am on Mixed Reality branch.

**Comment by RapukeMoana** [comment]
What version of all these tools did you use to build this?

**Comment by timGerken** [comment]
Unity 2017.2.0f3-MRTP3 and VS 2017 15.4.2.

Do you have entryies for VS100COMNTOOLS and VS140COMNTOOL anywhere in your registry?

Look here:
HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Session Manager\Environment

**Comment by RapukeMoana** [comment]
It appears not. What should I do. 
![galaxyexplorerissue](https://user-images.githubusercontent.com/11530296/32531720-5fbfd85a-c4aa-11e7-893d-441e03c3dca7.PNG)
This is outside my knowledge. Thanks for your help.

**Comment by jimshalo10** [comment]
My testing of the new release at
If you try to load  2017.2.0f3 MR 3 it will stop as UWP [ 2017.2.0f3](https://store.unity.com/download/thank-you?thank-you=personal&os=win&nid=437) is newest

Try [Demo](https://mtaulty.com/2017/11/04/butterflies-hello-world-demo-across-holographic-and-immersive-headsets/)

**Comment by timGerken** [comment]
@RapukeMoana ,
I'm not able to reproduce what you are seeing. That said, I have Visual Studio 2010, 2015 and 2017 installed and am currently using [Unity 2017.2.0p1-MRTP4](http://beta.unity3d.com/download/b1565bfe4a0c/download.html). Even if I remove VS100COMNTOOLS and VS140COMNTOOLS from my environment, I don't see the issue you are describing.

A couple more questions:
1) can you re-confirm that you are seeing this error when building from within Unity? If so, what are the settings in your Build Settings window?
2) is this from a clean clone of the repository?
`git clone http://github.com/microsoft/galaxyexplorer -b MixedReality`

**Comment by ChimeraScorn** [comment]
Does building a new app from Unity work on your machine?

**Comment by jimshalo10** [comment]
As instructed loading[g Unity 2017.2.0p1-MRTP4]( http://beta.unity3d.com/download/b1565bfe4a0c/download.html)
git clone http://github.com/microsoft/galaxyexplorer -b MixedReality


Built target being PC, everything build in VS2017 fine
Just need to know how to send directly to HP WMR headset, never do this before
Thanks

**Comment by RapukeMoana** [comment]
Thank you for your help. I had been working from the zip and as soon as I cloned from GitHub it all builds. Very much looking forward to building on GE. This describes our starting point which has been a design class collaboration so far and is now moving into building. https://trello.com/b/uaCT48b5/chronospatial
